xcopy \\Roadrunnerold\PAST\Software\MultiProgRunnerSvc\ProgRunnerSvc.exe \\proto-2\DMS_Programs\MultiProgRunnerSvc\ /Y
xcopy \\Roadrunnerold\PAST\Software\MultiProgRunnerSvc\ProgRunnerSvc.exe \\proto-3\DMS_Programs\MultiProgRunnerSvc\ /Y
xcopy \\Roadrunnerold\PAST\Software\MultiProgRunnerSvc\ProgRunnerSvc.exe \\proto-4\DMS_Programs\MultiProgRunnerSvc\ /Y
xcopy \\Roadrunnerold\PAST\Software\MultiProgRunnerSvc\ProgRunnerSvc.exe \\proto-5\DMS_Programs\MultiProgRunnerSvc\ /Y
xcopy \\Roadrunnerold\PAST\Software\MultiProgRunnerSvc\ProgRunnerSvc.exe \\proto-6\DMS_Programs\MultiProgRunnerSvc\ /Y
xcopy \\Roadrunnerold\PAST\Software\MultiProgRunnerSvc\ProgRunnerSvc.exe \\proto-7\DMS_Programs\MultiProgRunnerSvc\ /Y
xcopy \\Roadrunnerold\PAST\Software\MultiProgRunnerSvc\ProgRunnerSvc.exe \\proto-8\DMS_Programs\MultiProgRunnerSvc\ /Y
xcopy \\Roadrunnerold\PAST\Software\MultiProgRunnerSvc\ProgRunnerSvc.exe \\proto-9\DMS_Programs\MultiProgRunnerSvc\ /Y
xcopy \\Roadrunnerold\PAST\Software\MultiProgRunnerSvc\ProgRunnerSvc.exe \\proto-10\DMS_Programs\MultiProgRunnerSvc\ /Y
xcopy \\Roadrunnerold\PAST\Software\MultiProgRunnerSvc\ProgRunnerSvc.exe \\proto-11\DMS_Programs\MultiProgRunnerSvc\ /Y

xcopy \\Roadrunnerold\PAST\Software\MultiProgRunnerSvc\ProgRunnerSvc.exe \\seqcluster1\DMS_Programs\MultiProgRunnerSvc\ /Y
xcopy \\Roadrunnerold\PAST\Software\MultiProgRunnerSvc\ProgRunnerSvc.exe \\seqcluster2\DMS_Programs\MultiProgRunnerSvc\ /Y
xcopy \\Roadrunnerold\PAST\Software\MultiProgRunnerSvc\ProgRunnerSvc.exe \\seqcluster5\DMS_Programs\MultiProgRunnerSvc\ /Y

xcopy \\Roadrunnerold\PAST\Software\MultiProgRunnerSvc\ProgRunnerSvc.exe \\peaks1\DMS_Programs\MultiProgRunnerSvc\ /Y
xcopy \\Roadrunnerold\PAST\Software\MultiProgRunnerSvc\ProgRunnerSvc.exe \\Pub-24\DMS_Programs\MultiProgRunnerSvc\ /Y
xcopy \\Roadrunnerold\PAST\Software\MultiProgRunnerSvc\ProgRunnerSvc.exe \\Pub-26\DMS_Programs\MultiProgRunnerSvc\ /Y
xcopy \\Roadrunnerold\PAST\Software\MultiProgRunnerSvc\ProgRunnerSvc.exe \\Pub-27\DMS_Programs\MultiProgRunnerSvc\ /Y
xcopy \\Roadrunnerold\PAST\Software\MultiProgRunnerSvc\ProgRunnerSvc.exe \\Pub-28\DMS_Programs\MultiProgRunnerSvc\ /Y
xcopy \\Roadrunnerold\PAST\Software\MultiProgRunnerSvc\ProgRunnerSvc.exe \\Pub-29\DMS_Programs\MultiProgRunnerSvc\ /Y
xcopy \\Roadrunnerold\PAST\Software\MultiProgRunnerSvc\ProgRunnerSvc.exe \\Pub-30\DMS_Programs\MultiProgRunnerSvc\ /Y
xcopy \\Roadrunnerold\PAST\Software\MultiProgRunnerSvc\ProgRunnerSvc.exe \\Pub-31\DMS_Programs\MultiProgRunnerSvc\ /Y
xcopy \\Roadrunnerold\PAST\Software\MultiProgRunnerSvc\ProgRunnerSvc.exe \\Pub-32\DMS_Programs\MultiProgRunnerSvc\ /Y
xcopy \\Roadrunnerold\PAST\Software\MultiProgRunnerSvc\ProgRunnerSvc.exe \\Pub-33\DMS_Programs\MultiProgRunnerSvc\ /Y

xcopy \\Roadrunnerold\PAST\Software\MultiProgRunnerSvc\ProgRunnerSvc.exe \\Pub-36\DMS_Programs\MultiProgRunnerSvc\ /Y
xcopy \\Roadrunnerold\PAST\Software\MultiProgRunnerSvc\ProgRunnerSvc.exe \\Pub-37\DMS_Programs\MultiProgRunnerSvc\ /Y
xcopy \\Roadrunnerold\PAST\Software\MultiProgRunnerSvc\ProgRunnerSvc.exe \\Pub-38\DMS_Programs\MultiProgRunnerSvc\ /Y
xcopy \\Roadrunnerold\PAST\Software\MultiProgRunnerSvc\ProgRunnerSvc.exe \\Pub-39\DMS_Programs\MultiProgRunnerSvc\ /Y
xcopy \\Roadrunnerold\PAST\Software\MultiProgRunnerSvc\ProgRunnerSvc.exe \\Pub-40\DMS_Programs\MultiProgRunnerSvc\ /Y
xcopy \\Roadrunnerold\PAST\Software\MultiProgRunnerSvc\ProgRunnerSvc.exe \\Pub-41\DMS_Programs\MultiProgRunnerSvc\ /Y

xcopy \\Roadrunnerold\PAST\Software\MultiProgRunnerSvc\ProgRunnerSvc.exe \\Pub-44\DMS_Programs\MultiProgRunnerSvc\ /Y
xcopy \\Roadrunnerold\PAST\Software\MultiProgRunnerSvc\ProgRunnerSvc.exe \\Pub-45\DMS_Programs\MultiProgRunnerSvc\ /Y
xcopy \\Roadrunnerold\PAST\Software\MultiProgRunnerSvc\ProgRunnerSvc.exe \\Pub-46\DMS_Programs\MultiProgRunnerSvc\ /Y
xcopy \\Roadrunnerold\PAST\Software\MultiProgRunnerSvc\ProgRunnerSvc.exe \\Pub-47\DMS_Programs\MultiProgRunnerSvc\ /Y
xcopy \\Roadrunnerold\PAST\Software\MultiProgRunnerSvc\ProgRunnerSvc.exe \\Pub-48\DMS_Programs\MultiProgRunnerSvc\ /Y
xcopy \\Roadrunnerold\PAST\Software\MultiProgRunnerSvc\ProgRunnerSvc.exe \\Pub-49\DMS_Programs\MultiProgRunnerSvc\ /Y
xcopy \\Roadrunnerold\PAST\Software\MultiProgRunnerSvc\ProgRunnerSvc.exe \\Pub-50\DMS_Programs\MultiProgRunnerSvc\ /Y
xcopy \\Roadrunnerold\PAST\Software\MultiProgRunnerSvc\ProgRunnerSvc.exe \\Pub-51\DMS_Programs\MultiProgRunnerSvc\ /Y
xcopy \\Roadrunnerold\PAST\Software\MultiProgRunnerSvc\ProgRunnerSvc.exe \\Pub-52\DMS_Programs\MultiProgRunnerSvc\ /Y
xcopy \\Roadrunnerold\PAST\Software\MultiProgRunnerSvc\ProgRunnerSvc.exe \\Pub-53\DMS_Programs\MultiProgRunnerSvc\ /Y
xcopy \\Roadrunnerold\PAST\Software\MultiProgRunnerSvc\ProgRunnerSvc.exe \\Pub-54\DMS_Programs\MultiProgRunnerSvc\ /Y
xcopy \\Roadrunnerold\PAST\Software\MultiProgRunnerSvc\ProgRunnerSvc.exe \\Pub-55\DMS_Programs\MultiProgRunnerSvc\ /Y
xcopy \\Roadrunnerold\PAST\Software\MultiProgRunnerSvc\ProgRunnerSvc.exe \\Pub-56\DMS_Programs\MultiProgRunnerSvc\ /Y
xcopy \\Roadrunnerold\PAST\Software\MultiProgRunnerSvc\ProgRunnerSvc.exe \\Pub-57\DMS_Programs\MultiProgRunnerSvc\ /Y
xcopy \\Roadrunnerold\PAST\Software\MultiProgRunnerSvc\ProgRunnerSvc.exe \\Pub-58\DMS_Programs\MultiProgRunnerSvc\ /Y
xcopy \\Roadrunnerold\PAST\Software\MultiProgRunnerSvc\ProgRunnerSvc.exe \\Pub-59\DMS_Programs\MultiProgRunnerSvc\ /Y
xcopy \\Roadrunnerold\PAST\Software\MultiProgRunnerSvc\ProgRunnerSvc.exe \\Pub-60\DMS_Programs\MultiProgRunnerSvc\ /Y
xcopy \\Roadrunnerold\PAST\Software\MultiProgRunnerSvc\ProgRunnerSvc.exe \\Pub-61\DMS_Programs\MultiProgRunnerSvc\ /Y
xcopy \\Roadrunnerold\PAST\Software\MultiProgRunnerSvc\ProgRunnerSvc.exe \\Pub-62\DMS_Programs\MultiProgRunnerSvc\ /Y
xcopy \\Roadrunnerold\PAST\Software\MultiProgRunnerSvc\ProgRunnerSvc.exe \\Pub-63\DMS_Programs\MultiProgRunnerSvc\ /Y
xcopy \\Roadrunnerold\PAST\Software\MultiProgRunnerSvc\ProgRunnerSvc.exe \\Pub-64\DMS_Programs\MultiProgRunnerSvc\ /Y
xcopy \\Roadrunnerold\PAST\Software\MultiProgRunnerSvc\ProgRunnerSvc.exe \\Pub-65\DMS_Programs\MultiProgRunnerSvc\ /Y
xcopy \\Roadrunnerold\PAST\Software\MultiProgRunnerSvc\ProgRunnerSvc.exe \\Pub-66\DMS_Programs\MultiProgRunnerSvc\ /Y
xcopy \\Roadrunnerold\PAST\Software\MultiProgRunnerSvc\ProgRunnerSvc.exe \\Pub-67\DMS_Programs\MultiProgRunnerSvc\ /Y
xcopy \\Roadrunnerold\PAST\Software\MultiProgRunnerSvc\ProgRunnerSvc.exe \\Pub-68\DMS_Programs\MultiProgRunnerSvc\ /Y
xcopy \\Roadrunnerold\PAST\Software\MultiProgRunnerSvc\ProgRunnerSvc.exe \\Pub-69\DMS_Programs\MultiProgRunnerSvc\ /Y
xcopy \\Roadrunnerold\PAST\Software\MultiProgRunnerSvc\ProgRunnerSvc.exe \\Pub-70\DMS_Programs\MultiProgRunnerSvc\ /Y
xcopy \\Roadrunnerold\PAST\Software\MultiProgRunnerSvc\ProgRunnerSvc.exe \\Pub-71\DMS_Programs\MultiProgRunnerSvc\ /Y
xcopy \\Roadrunnerold\PAST\Software\MultiProgRunnerSvc\ProgRunnerSvc.exe \\Pub-72\DMS_Programs\MultiProgRunnerSvc\ /Y
xcopy \\Roadrunnerold\PAST\Software\MultiProgRunnerSvc\ProgRunnerSvc.exe \\Pub-73\DMS_Programs\MultiProgRunnerSvc\ /Y
xcopy \\Roadrunnerold\PAST\Software\MultiProgRunnerSvc\ProgRunnerSvc.exe \\Pub-74\DMS_Programs\MultiProgRunnerSvc\ /Y
xcopy \\Roadrunnerold\PAST\Software\MultiProgRunnerSvc\ProgRunnerSvc.exe \\Pub-75\DMS_Programs\MultiProgRunnerSvc\ /Y
xcopy \\Roadrunnerold\PAST\Software\MultiProgRunnerSvc\ProgRunnerSvc.exe \\Pub-76\DMS_Programs\MultiProgRunnerSvc\ /Y
xcopy \\Roadrunnerold\PAST\Software\MultiProgRunnerSvc\ProgRunnerSvc.exe \\Pub-77\DMS_Programs\MultiProgRunnerSvc\ /Y
xcopy \\Roadrunnerold\PAST\Software\MultiProgRunnerSvc\ProgRunnerSvc.exe \\Pub-78\DMS_Programs\MultiProgRunnerSvc\ /Y
xcopy \\Roadrunnerold\PAST\Software\MultiProgRunnerSvc\ProgRunnerSvc.exe \\Pub-79\DMS_Programs\MultiProgRunnerSvc\ /Y
xcopy \\Roadrunnerold\PAST\Software\MultiProgRunnerSvc\ProgRunnerSvc.exe \\Pub-80\DMS_Programs\MultiProgRunnerSvc\ /Y
xcopy \\Roadrunnerold\PAST\Software\MultiProgRunnerSvc\ProgRunnerSvc.exe \\Pub-81\DMS_Programs\MultiProgRunnerSvc\ /Y
xcopy \\Roadrunnerold\PAST\Software\MultiProgRunnerSvc\ProgRunnerSvc.exe \\Pub-82\DMS_Programs\MultiProgRunnerSvc\ /Y
xcopy \\Roadrunnerold\PAST\Software\MultiProgRunnerSvc\ProgRunnerSvc.exe \\Pub-83\DMS_Programs\MultiProgRunnerSvc\ /Y
xcopy \\Roadrunnerold\PAST\Software\MultiProgRunnerSvc\ProgRunnerSvc.exe \\Pub-84\DMS_Programs\MultiProgRunnerSvc\ /Y
xcopy \\Roadrunnerold\PAST\Software\MultiProgRunnerSvc\ProgRunnerSvc.exe \\Pub-85\DMS_Programs\MultiProgRunnerSvc\ /Y
xcopy \\Roadrunnerold\PAST\Software\MultiProgRunnerSvc\ProgRunnerSvc.exe \\Pub-86\DMS_Programs\MultiProgRunnerSvc\ /Y
xcopy \\Roadrunnerold\PAST\Software\MultiProgRunnerSvc\ProgRunnerSvc.exe \\Pub-87\DMS_Programs\MultiProgRunnerSvc\ /Y
xcopy \\Roadrunnerold\PAST\Software\MultiProgRunnerSvc\ProgRunnerSvc.exe \\Pub-88\DMS_Programs\MultiProgRunnerSvc\ /Y
xcopy \\Roadrunnerold\PAST\Software\MultiProgRunnerSvc\ProgRunnerSvc.exe \\Pub-89\DMS_Programs\MultiProgRunnerSvc\ /Y
xcopy \\Roadrunnerold\PAST\Software\MultiProgRunnerSvc\ProgRunnerSvc.exe \\Pub-90\DMS_Programs\MultiProgRunnerSvc\ /Y
xcopy \\Roadrunnerold\PAST\Software\MultiProgRunnerSvc\ProgRunnerSvc.exe \\Pub-91\DMS_Programs\MultiProgRunnerSvc\ /Y
xcopy \\Roadrunnerold\PAST\Software\MultiProgRunnerSvc\ProgRunnerSvc.exe \\Pub-92\DMS_Programs\MultiProgRunnerSvc\ /Y
xcopy \\Roadrunnerold\PAST\Software\MultiProgRunnerSvc\ProgRunnerSvc.exe \\Pub-93\DMS_Programs\MultiProgRunnerSvc\ /Y
xcopy \\Roadrunnerold\PAST\Software\MultiProgRunnerSvc\ProgRunnerSvc.exe \\Pub-94\DMS_Programs\MultiProgRunnerSvc\ /Y
xcopy \\Roadrunnerold\PAST\Software\MultiProgRunnerSvc\ProgRunnerSvc.exe \\Pub-95\DMS_Programs\MultiProgRunnerSvc\ /Y
xcopy \\Roadrunnerold\PAST\Software\MultiProgRunnerSvc\ProgRunnerSvc.exe \\Pub-96\DMS_Programs\MultiProgRunnerSvc\ /Y
xcopy \\Roadrunnerold\PAST\Software\MultiProgRunnerSvc\ProgRunnerSvc.exe \\Pub-97\DMS_Programs\MultiProgRunnerSvc\ /Y

xcopy \\Roadrunnerold\PAST\Software\MultiProgRunnerSvc\ProgRunnerSvc.exe \\mallard\DMS_Programs\MultiProgRunnerSvc\ /Y
