@echo off

call DeleteOldLogsWork.bat \\proto-2\DMS_Programs\MultiProgRunnerSvc\
call DeleteOldLogsWork.bat \\proto-3\DMS_Programs\MultiProgRunnerSvc\
call DeleteOldLogsWork.bat \\proto-4\DMS_Programs\MultiProgRunnerSvc\
call DeleteOldLogsWork.bat \\proto-5\DMS_Programs\MultiProgRunnerSvc\
call DeleteOldLogsWork.bat \\proto-6\DMS_Programs\MultiProgRunnerSvc\
call DeleteOldLogsWork.bat \\proto-7\DMS_Programs\MultiProgRunnerSvc\
call DeleteOldLogsWork.bat \\proto-8\DMS_Programs\MultiProgRunnerSvc\
call DeleteOldLogsWork.bat \\proto-9\DMS_Programs\MultiProgRunnerSvc\
call DeleteOldLogsWork.bat \\proto-10\DMS_Programs\MultiProgRunnerSvc\
call DeleteOldLogsWork.bat \\proto-11\DMS_Programs\MultiProgRunnerSvc\

call DeleteOldLogsWork.bat \\seqcluster1\DMS_Programs\MultiProgRunnerSvc\
call DeleteOldLogsWork.bat \\seqcluster2\DMS_Programs\MultiProgRunnerSvc\
call DeleteOldLogsWork.bat \\seqcluster5\DMS_Programs\MultiProgRunnerSvc\

call DeleteOldLogsWork.bat \\peaks1\DMS_Programs\MultiProgRunnerSvc\
call DeleteOldLogsWork.bat \\Pub-24\DMS_Programs\MultiProgRunnerSvc\
call DeleteOldLogsWork.bat \\Pub-26\DMS_Programs\MultiProgRunnerSvc\
call DeleteOldLogsWork.bat \\Pub-27\DMS_Programs\MultiProgRunnerSvc\
call DeleteOldLogsWork.bat \\Pub-28\DMS_Programs\MultiProgRunnerSvc\
call DeleteOldLogsWork.bat \\Pub-29\DMS_Programs\MultiProgRunnerSvc\
call DeleteOldLogsWork.bat \\Pub-30\DMS_Programs\MultiProgRunnerSvc\
call DeleteOldLogsWork.bat \\Pub-31\DMS_Programs\MultiProgRunnerSvc\
call DeleteOldLogsWork.bat \\Pub-32\DMS_Programs\MultiProgRunnerSvc\
call DeleteOldLogsWork.bat \\Pub-33\DMS_Programs\MultiProgRunnerSvc\

call DeleteOldLogsWork.bat \\Pub-36\DMS_Programs\MultiProgRunnerSvc\
call DeleteOldLogsWork.bat \\Pub-37\DMS_Programs\MultiProgRunnerSvc\
call DeleteOldLogsWork.bat \\Pub-38\DMS_Programs\MultiProgRunnerSvc\
call DeleteOldLogsWork.bat \\Pub-39\DMS_Programs\MultiProgRunnerSvc\
call DeleteOldLogsWork.bat \\Pub-40\DMS_Programs\MultiProgRunnerSvc\
call DeleteOldLogsWork.bat \\Pub-41\DMS_Programs\MultiProgRunnerSvc\

call DeleteOldLogsWork.bat \\Pub-44\DMS_Programs\MultiProgRunnerSvc\
call DeleteOldLogsWork.bat \\Pub-45\DMS_Programs\MultiProgRunnerSvc\
call DeleteOldLogsWork.bat \\Pub-46\DMS_Programs\MultiProgRunnerSvc\
call DeleteOldLogsWork.bat \\Pub-47\DMS_Programs\MultiProgRunnerSvc\
call DeleteOldLogsWork.bat \\Pub-48\DMS_Programs\MultiProgRunnerSvc\
call DeleteOldLogsWork.bat \\Pub-49\DMS_Programs\MultiProgRunnerSvc\
call DeleteOldLogsWork.bat \\Pub-50\DMS_Programs\MultiProgRunnerSvc\
call DeleteOldLogsWork.bat \\Pub-51\DMS_Programs\MultiProgRunnerSvc\
call DeleteOldLogsWork.bat \\Pub-52\DMS_Programs\MultiProgRunnerSvc\
call DeleteOldLogsWork.bat \\Pub-53\DMS_Programs\MultiProgRunnerSvc\
call DeleteOldLogsWork.bat \\Pub-54\DMS_Programs\MultiProgRunnerSvc\
call DeleteOldLogsWork.bat \\Pub-55\DMS_Programs\MultiProgRunnerSvc\
call DeleteOldLogsWork.bat \\Pub-56\DMS_Programs\MultiProgRunnerSvc\
call DeleteOldLogsWork.bat \\Pub-57\DMS_Programs\MultiProgRunnerSvc\
call DeleteOldLogsWork.bat \\Pub-58\DMS_Programs\MultiProgRunnerSvc\
call DeleteOldLogsWork.bat \\Pub-59\DMS_Programs\MultiProgRunnerSvc\
call DeleteOldLogsWork.bat \\Pub-60\DMS_Programs\MultiProgRunnerSvc\
call DeleteOldLogsWork.bat \\Pub-61\DMS_Programs\MultiProgRunnerSvc\
call DeleteOldLogsWork.bat \\Pub-62\DMS_Programs\MultiProgRunnerSvc\
call DeleteOldLogsWork.bat \\Pub-63\DMS_Programs\MultiProgRunnerSvc\
call DeleteOldLogsWork.bat \\Pub-64\DMS_Programs\MultiProgRunnerSvc\
call DeleteOldLogsWork.bat \\Pub-65\DMS_Programs\MultiProgRunnerSvc\
call DeleteOldLogsWork.bat \\Pub-66\DMS_Programs\MultiProgRunnerSvc\
call DeleteOldLogsWork.bat \\Pub-67\DMS_Programs\MultiProgRunnerSvc\
call DeleteOldLogsWork.bat \\Pub-68\DMS_Programs\MultiProgRunnerSvc\
call DeleteOldLogsWork.bat \\Pub-69\DMS_Programs\MultiProgRunnerSvc\
call DeleteOldLogsWork.bat \\Pub-70\DMS_Programs\MultiProgRunnerSvc\
call DeleteOldLogsWork.bat \\Pub-71\DMS_Programs\MultiProgRunnerSvc\
call DeleteOldLogsWork.bat \\Pub-72\DMS_Programs\MultiProgRunnerSvc\
call DeleteOldLogsWork.bat \\Pub-73\DMS_Programs\MultiProgRunnerSvc\
call DeleteOldLogsWork.bat \\Pub-74\DMS_Programs\MultiProgRunnerSvc\
call DeleteOldLogsWork.bat \\Pub-75\DMS_Programs\MultiProgRunnerSvc\
call DeleteOldLogsWork.bat \\Pub-76\DMS_Programs\MultiProgRunnerSvc\
call DeleteOldLogsWork.bat \\Pub-77\DMS_Programs\MultiProgRunnerSvc\
call DeleteOldLogsWork.bat \\Pub-78\DMS_Programs\MultiProgRunnerSvc\
call DeleteOldLogsWork.bat \\Pub-79\DMS_Programs\MultiProgRunnerSvc\
call DeleteOldLogsWork.bat \\Pub-80\DMS_Programs\MultiProgRunnerSvc\
call DeleteOldLogsWork.bat \\Pub-81\DMS_Programs\MultiProgRunnerSvc\
call DeleteOldLogsWork.bat \\Pub-82\DMS_Programs\MultiProgRunnerSvc\
call DeleteOldLogsWork.bat \\Pub-83\DMS_Programs\MultiProgRunnerSvc\
call DeleteOldLogsWork.bat \\Pub-84\DMS_Programs\MultiProgRunnerSvc\
call DeleteOldLogsWork.bat \\Pub-85\DMS_Programs\MultiProgRunnerSvc\
call DeleteOldLogsWork.bat \\Pub-86\DMS_Programs\MultiProgRunnerSvc\
call DeleteOldLogsWork.bat \\Pub-87\DMS_Programs\MultiProgRunnerSvc\
call DeleteOldLogsWork.bat \\Pub-88\DMS_Programs\MultiProgRunnerSvc\
call DeleteOldLogsWork.bat \\Pub-89\DMS_Programs\MultiProgRunnerSvc\
call DeleteOldLogsWork.bat \\Pub-90\DMS_Programs\MultiProgRunnerSvc\
call DeleteOldLogsWork.bat \\Pub-91\DMS_Programs\MultiProgRunnerSvc\
call DeleteOldLogsWork.bat \\Pub-92\DMS_Programs\MultiProgRunnerSvc\
call DeleteOldLogsWork.bat \\Pub-93\DMS_Programs\MultiProgRunnerSvc\
call DeleteOldLogsWork.bat \\Pub-94\DMS_Programs\MultiProgRunnerSvc\
call DeleteOldLogsWork.bat \\Pub-95\DMS_Programs\MultiProgRunnerSvc\
call DeleteOldLogsWork.bat \\Pub-96\DMS_Programs\MultiProgRunnerSvc\
call DeleteOldLogsWork.bat \\Pub-97\DMS_Programs\MultiProgRunnerSvc\

call DeleteOldLogsWork.bat \\mallard\DMS_Programs\MultiProgRunnerSvc\
